export const SEARCH_START = "SEARCH_START";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_COMPLETE = "SEARCH_COMPLETE";

export const SEARCH_BY_ID_START = "SEARCH_BY_ID_START";
export const SEARCH_BY_ID_ERROR = "SEARCH_BY_ID_ERROR";
export const SEARCH_BY_ID_COMPLETE = "SEARCH_BY_ID_COMPLETE";
